[project]
name = "y4"
version = "0.1.1"
dependencies = [
    "jq",
    "pyyaml",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
y4 = "y4.__main__:main"
